host: "localhost"
port: 6379
db: 0
password: ""
decodedResponses: False

newImagePubSubChannel: "imageReady"
newImageMsgRoot: "image_"

newAudioPubSubChannel: "audioReady"
newAudioMsgRoot: "audio_"

imageHsetRoot: "image_"
imageHsetB64Field: "b64"
imageHsetFacialResultField: "FEA"
imageHsetPoseResultField: "PEA"

audioHsetRoot: "audio_"
audioHsetB64Field: "b64"
audioHsetVocalResultField: "VEA"

FacialQueue: "FEAQueue"
PoseQueue: "PEAQueue"
VocalChannel: "VEAReady"